spring.application.name=Awesome_Travel

# \uB3C4\uBA54\uC778
# awesometravel.domain=dev
app.frontend.url=https://www.awesometravel.com


# DB \uC5F0\uACB0
spring.datasource.url=jdbc:mariadb://localhost:3307/awesome
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# spring.datasource.username=dev
# spring.datasource.password=dev

#create,create-drop,update,validate,none
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# SQL \uCFFC\uB9AC \uCF58\uC194 \uCD9C\uB825
spring.jpa.show-sql=true

# SSL \uC124\uC815
server.port=443
server.http2.enabled=true
server.ssl.enabled=true
server.ssl.key-store=certificate.p12
server.ssl.key-store-type=PKCS12
# server.ssl.key-store-password=dev

# dev \uBCC0\uC218 \uC124\uC815
spring.profiles.active=dev

#email \uC124\uC815
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


spring.config.import=classpath:application-h2.properties,classpath:application-oauth.properties


