spring.application.name=Awesome_Travel

# 도메인
# awesometravel.domain=dev

# DB 연결
spring.datasource.url=jdbc:mariadb://localhost:3307/awesome
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# spring.datasource.username=dev
# spring.datasource.password=dev

#create,create-drop,update,validate,none
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# SQL 쿼리 콘솔 출력
spring.jpa.show-sql=true

# SSL 설정
server.port=443
server.http2.enabled=true
server.ssl.enabled=true
server.ssl.key-store=certificate.p12
server.ssl.key-store-type=PKCS12
# server.ssl.key-store-password=dev

# dev 변수 설정
spring.profiles.active=dev

spring.config.import=classpath:application-h2.properties