spring.application.name=Awesome_Travel

# \uB3C4\uBA54\uC778
# awesometravel.domain=dev
app.frontend.url=https://www.awesometravel.com


# DB \uC5F0\uACB0
spring.datasource.url=jdbc:mariadb://localhost:3306/awesome
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=awesome
spring.datasource.password=travel

#create,create-drop,update,validate,none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:mock/air.sql,classpath:mock/city_code.sql,classpath:mock/hotel.sql,classpath:mock/product.sql,classpath:mock/tour.sql

# SQL \uCFFC\uB9AC \uCF58\uC194 \uCD9C\uB825
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# SSL \uC124\uC815
server.port=9091
# server.http2.enabled=true
server.ssl.enabled=true
server.ssl.key-store=certificate.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=kyj0407

# dev \uBCC0\uC218 \uC124\uC815
spring.profiles.active=dev

#email \uC124\uC815
spring.mail.host=smtp.gmail.com
spring.mail.port=9587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


spring.config.import=classpath:application-h2.properties,classpath:application-oauth.properties

iconLocation=src/main/java/renewal/common/static/icon